### PR TITLE
Connection recycling + timestamp

### PR DESCRIPTION
**Pull request by hawkeng**
Added a kind of rustic way to reuse an existing connection. Useful when iterating over an array of schema names to generate the joi schemas.

Also added support for _timestamp_ mysql field on mapping

### CODE REVIEW

**Comment by TehShrike** [comment]
Timestamp addition looks good to me.

Exposing `connection` does open up some other compatibility issues in the future - if the `mysql` module's API ever changes (or if it's changed over the last couple years - this library currently depends on an older version), then it could break.

Did you run into a real-world case where reconnecting every time was an issue?

I'm not too opposed to it, but the readme should include something like "You may also pass in an optional `connection` property which must be a [`mysql`](https://github.com/mysqljs/mysql) connection instance" so people know how they can get make their own connection.

**Comment by hawkeng** [comment]
> (or if it's changed over the last couple years - this library currently depends on an older version)

I'm currently using the lastest version of mysql, so its compatible so far

> Did you run into a real-world case where reconnecting every time was an issue?

Mm not really, actually my priority is to get the timestamp field compatibility but since I'll be running joi-sql with a considerable amount of schemas I thought it could be good to reuse the connection (which I instantiate before since I first create the schema and load some data).

I also added an example in the readme indicating that exact thing you mention about an optional connection.

**Comment by TehShrike** [comment]
The example doesn't mention where `mysql.createConnection` comes from, though - even if there aren't many major competing MySQL libraries for node.js, we should point people to the correct module (and call out the property name explicitly, too).  I care about that more than giving an example (most people probably won't specify a connection, so I'm fine with documenting the property without giving an example).

Otherwise, I'm down to merge, I can release on Monday.

**Comment by TehShrike** [comment]
I'm still happy to merge this

**Comment by TehShrike** [comment]
Published as 1.3.0

**Pull request merged**
